# Generated by Django 6.1 on 2026-08-14 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_phase1_cms_notifications_proofs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_notific_recipie_28b188_idx',
            old_name='api_notific_recipie_idx',
        ),
    ]
